### ISSUE TITLE
Images are not shown in output

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/judge-turtle#66]
When submitting solutions for the Turtle judge, I can't seem to get the images to work:

![image](https://user-images.githubusercontent.com/1756811/224061232-3949ba24-ec7e-4072-8334-2c6aec1811fa.png)

Tested in both Firefox and Chrome.

(Not entirely sure if this is a turtle judge issue or a Dodona issue, but I'll move the issue to the correct repo if necessary)

**Comment by BTWS2** [comment]
Thank you for notifying me. Images form submissions that worked correctly in the past are also gone (e.g. https://dodona.ugent.be/nl/submissions/11622640/), but the code from the judge didn't change. This leads me to believe this is a Dodona issue.

**Comment by jorg-vr** [comment]
Summary of slack discussion:

`data:image/svg+xml` is no longer supported due to security concerns (see https://github.com/rails/rails-html-sanitizer/pull/147)

I suggest to render svg's inline instead of as an image. This allows for proper sanitizing by rails.

**Comment by BTWS2** [comment]
`data:image/svg+xml` is no longer supported due to security concerns. SVG's are now shown inline. This commit fixed the render: https://github.com/dodona-edu/judge-turtle/commit/39bd9cfd052d5de8ccef5482e05c9c6be6bba081.

The `polyline` tag wasn't allowed as a tag. This was fixed by: https://github.com/dodona-edu/dodona/pull/5853.
